### ISSUE TITLE
java.lang.UnsupportedClassVersionError: net/intellij/plugins/sexyeditor/SexyEditor : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by luoxiaoy** [igr/idea-sexyeditor#14]
java.lang.UnsupportedClassVersionError: net/intellij/plugins/sexyeditor/SexyEditor : Unsupported major.minor version 52.0

**Comment by igorspasic** [comment]
Hey @luoxiaoy This is really strange; which version of IDEA you have?
