### ISSUE TITLE
Feature request: support multiple insert with *

### ISSUE THREAD

**Issue by MarisaKirisame** [igr/idea-sexyeditor#15]
So for example, I should be able to do C:\Users\marisa\Downloads\*.jpg in FileList instead of adding them one by one

**Comment by igr** [comment]
Sorry, I would need to pass on this request :(
It's simply a bit more work than I can work on, and, with the latest changes, you can simply select multiple files at once on import.

**Comment by MarisaKirisame** [comment]
> with the latest changes, you can simply select multiple files at once on import.
that's great to hear! thx for your work
