### ISSUE TITLE
[imrovement] shadows under text

### ISSUE THREAD

**Issue by mtancoigne** [igr/idea-sexyeditor#17]
Hi ! 
I wonder if t's easy to add a text shadow under the code, so it's still readable on any wallpaper ?

The idea comes from this [Atom plugin](https://atom.io/packages/editor-background)

**Comment by igr** [comment]
Hey @mtancoigne nice idea, but I doubt it is easy :( The thing is that I have control over the background and background only. In order to have the shadow, we would need to manipulate the way idea is actually drawing the code, and I am almost sure that there is no way how to turn off that.

**Comment by mtancoigne** [comment]
Hi !
Yep, i understand, it seems easy in atom, as the code is styled with CSS. I don't know how it work on idea. Maybe a temporary workaround would be to manually set a background color for the code, in a custom theme...

**Comment by igr** [comment]
I will close this as there is no practical way to do so; we have control only of the background drawing, not related to whatever is on top of it.

**Comment by mtancoigne** [comment]
no problem, I understand.
