### ISSUE TITLE
[improvement] - "zoom to fit" display option

### ISSUE THREAD

**Issue by mtancoigne** [igr/idea-sexyeditor#18]
An option to display the background zoomed would be great: I have big images, so I only see a portion of them... An option that would fit the display area  at 100% of image height or width, so the image is always mostly 100% visible should be great ! I think it's called "zoom to fit" in some oses.

**Comment by igr** [comment]
Make sense!

**Comment by mtancoigne** [comment]
Thank you :)

**Comment by igr** [comment]
Enjoy it ;)))
