### ISSUE TITLE
Draw Image under text

### ISSUE THREAD

**Issue by WeslomPo** [igr/idea-sexyeditor#20]
Hi! Can you draw image under the text, not over? Now text looks like it have an alpha.

**Comment by igr** [comment]
Hi there!

Sorry, not sure if I understand... I do drive the image under the text, in the background. I don't even deal with the text at all :)

Try changing the opacity of the photo. I also use photos that are darker (or black-white) to match the Dracula theme. In your case, it can only be a visual effect that appears so.

Or you can send me the screenshot to see what you mean?

**Comment by igr** [comment]
Closing this one as it is not doable.
